version: '2'
catalog:
  name: 24print v3
  version: 1.0.0
  description: |
    24print.eu in Docker containers, Shop, Render and Static
  questions: #Used to request user input for configuration options
    - variable: PROJECT_NAME # A single word that is used to pair the question and answer.
      label: Project name # The "question" to be answered.
      description: |
        Name of project (RootDir)
      # The description of the question to show the user how to answer the question.
      default: 24print_v3 # (Optional) A default value that will be pre-populated into the UI
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected
    - variable: ENV_VER # A single word that is used to pair the question and answer.
      label: Project environment (public/stable/develop) # The "question" to be answered.
      description: |
        Project deploy version
      # The description of the question to show the user how to answer the question.
      default: public # (Optional) A default value that will be pre-populated into the UI
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: enum # How the questions are formatted and types of response expected
      options:
        - public
        - preview
        - develop/prim
        - develop/zradicka
        - develop/najman
    - variable: GIT_SERVER # A single word that is used to pair the question and answer.
      label: Project git server # The "question" to be answered.
      description: |
        Where is project repository
      # The description of the question to show the user how to answer the question.
      default: bitbucket.org # (Optional) A default value that will be pre-populated into the UI
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected
    - variable: GIT_REPO # A single word that is used to pair the question and answer.
      label: Project git repo # The "question" to be answered.
      description: |
        Project repository
      # The description of the question to show the user how to answer the question.
      default: infas/24print_v3 # (Optional) A default value that will be pre-populated into the UI
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected
    - variable: GIT_BRANCH # A single word that is used to pair the question and answer.
      label: Set git branch # The "question" to be answered.
      description: |
        Project deploy branche
      # The description of the question to show the user how to answer the question.
      default: master # (Optional) A default value that will be pre-populated into the UI
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected

services:
  fpm:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  nginx:
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
